'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Dashboard
    dashboardOverview: "Dashboard Overview",
    totalStudents: "Total Students",
    activePackages: "Active Packages",
    classesToday: "Classes Today",
    recentRescheduledClasses: "Recent Rescheduled Classes",
    from: "From",
    to: "To",
    
    // Schedule page
    schedule: "Schedule",
    teacherSchedule: "Teacher Schedule",
    givenClasses: "Given Classes",
    startDate: "Start Date",
    endDate: "End Date",
    teacher: "Teacher",
    date: "Date",
    time: "Time",
    title: "Title",
    students: "Students",
    noScheduleData: "No scheduled classes found for the selected period.",
    noGivenClassesData: "No completed classes found for the selected period.",
    showFilters: "Show Filters",
    hideFilters: "Hide Filters",
    resetFilters: "Reset Filters",
    allTeachers: "All Teachers",
    noFeedback: "No feedback",
    updateTeachers: "Update Teachers",
    
    // Students page
    studentsManagement: "Students Management",
    addNewStudent: "Add New Student",
    name: "Name",
    username: "Username",
    location: "Location",
    package: "Package",
    classesLeft: "Classes Left",
    joinDate: "Join Date",
    actions: "Actions",
    classes: "classes",
    studentDetails: "Student Details",
    close: "Close",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    editStudent: "Edit Student",
    surname: "Surname",
    password: "Password",
    city: "City",
    country: "Country",
    packageType: "Package Type",
    classHistory: "Class History",
    totalClassesTaken: "Total Classes Taken",
    rescheduledClasses: "Rescheduled Classes",
    times: "times",
    
    // Sidebar translations
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    teacherManagement: "Teacher Management",
    logout: "Logout",
    appName: "YekaCoach",
    packageManagement: 'Package Management',
    addNewPackage: 'Add New Package',
    editPackage: 'Edit Package',
    packageName: 'Package Name',
    description: 'Description',
    classesPerMonth: 'Classes per Month',
    maxReschedules: 'Max Reschedules',
    price: 'Price',
    status: 'Status',
    save: 'Save',
    classCalendar: "Class Calendar",
    packageDetails: "Package Details",
    validUntil: "Valid until",
    classesRemaining: "Classes Remaining",
    reschedulesAvailable: "Reschedules Available",
    rescheduleClass: "Reschedule Class",
    confirmReschedule: "Confirm Reschedule",
    nextClass: "Next Class",
    canReschedule: "Can Reschedule",
    totalClasses: "Total Classes",
    upcomingClass: "Upcoming Class",
    
    // Student Profile Page
    profile: "My Profile",
    editProfile: "Edit Profile",
    changePassword: "Change Password",
    personalInfo: "Personal Info",
    history: "History",
    contactInformation: "Contact Information",
    packageInformation: "Package Information",
    period: "Period",
    upcomingClasses: "Upcoming Classes",
    completedClasses: "Completed Classes",
    feedback: "Feedback",
    reschedulable: "Reschedulable",
    reschedule: "Reschedule",
    noUpcomingClasses: "No upcoming classes scheduled",
    completed: "Completed",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match",
    email: "Email",
    phone: "Phone",
    
    // Student Dashboard
    studentDashboard: "Student Dashboard",
    remainingClasses: "Remaining Classes",
    rescheduleCredits: "Reschedule Credits",
    packageValidUntil: "Package Valid Until",
    classSchedule: "Class Schedule",
    outOf: "Out of",
    creditsAllowed: "credits allowed",
    selectNewDate: "Select New Date",
    selectNewTime: "Select New Time",
    rescheduleWarning: "* You must reschedule at least 2 hours before the class starts",
    confirmReschedule: "Confirm Reschedule",
    rescheduleNotAllowed: "This class cannot be rescheduled as it has already been completed.",
    rescheduleTimeLimit: "Classes can only be rescheduled at least 2 hours before they start.",
    joined: "Joined",
    contactAdminForChanges: "Please contact the administrator if you need to update your profile information.",
    
    // Login page
    login: "Login",
    loggingIn: "Logging in...",
    rememberMe: "Remember me",
    
    // Landing page
    startNow: "Start Now",
    loginNow: "Login Now",
    backToHome: "Back to Home",
    ourFeatures: "Our Features",
    singingLessons: "Singing Lessons",
    flexibleScheduling: "Flexible Scheduling",
    progressTracking: "Progress Tracking",
    whatOurStudentsSay: "What Our Students Say",
    readyToStartJourney: "Ready to Start Your Singing Journey?",
    joinToday: "Join YekaCoach Academy today and transform your singing abilities with expert guidance.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All rights reserved.",
    
    // Password and authentication
    passwordChangeSuccess: "Password changed successfully!",
    changePasswordFailed: "Failed to change password. Please check your current password and try again.",
    saving: "Saving...",
    loginFailed: "Login failed. Please check your credentials and try again.",
    accountLocked: "Your account has been locked due to too many failed login attempts. Please contact an administrator.",
    accountDisabled: "Your account has been disabled. Please contact an administrator.",
    accountInactive: "Your account has been deactivated by the administrator. Please contact support for assistance.",
    sessionExpired: "Your session has expired. Please log in again.",
    logoutSuccess: "You have been successfully logged out.",
    unauthorized: "You are not authorized to access this page.",
    wrongPortalStudent: "Access denied. This portal is for students only. Please use the internal login system for staff access.",
    wrongPortalInternal: "Access denied. This portal is for staff only. Please use the student login portal.",
    
    // General UI
    loading: "Loading, please wait...",
    switchToSpanish: "Switch to Spanish",
    switchToEnglish: "Switch to English",
    
    // Form validation
    usernameRequired: "Username is required",
    passwordRequired: "Password is required",
    currentPasswordRequired: "Current password is required",
    newPasswordRequired: "New password is required",
    confirmPasswordRequired: "Please confirm your password",
    passwordMinLength: "Password must be at least 8 characters",
    
    // Notifications and messages
    loginSuccess: "Login successful! Welcome back.",
    loginFailed: "Login failed. Please check your credentials and try again.",
    unexpectedError: "An unexpected error occurred. Please try again later.",
    changesSaved: "Changes saved successfully!",
    
    // Student Dashboard (adding missing translations)
    currentPackage: "Current Package",
    noPackage: "No Package",
    scheduledClasses: "Scheduled Classes",
    passedClasses: "Passed Classes",
    dateFormat: "dddd, MMMM D, YYYY",
    timeFormat: "h:mm A",
    shortDateFormat: "MMM D, YYYY",
    minutes: "minutes",
    currentClass: "Current class",
    class: "class",
    today: "TODAY",
    fullScreen: "Full Screen",
    exitFullScreen: "Exit Full Screen",
    loading: "Loading your classes...",
    noClasses: "No classes scheduled",
    noClassesDescription: "You don't have any classes scheduled at the moment.",
    rescheduled: "Rescheduled",
    cantReschedule: "Can't Reschedule",
    attended: "Attended",
    errorLoadingData: "Error loading your data.",
    rescheduleSuccess: "Class rescheduled successfully",
    rescheduleError: "Error rescheduling class. Please try again.",
    
    // Additional students page translations
    refresh: "Refresh",
    refreshShort: "Refresh",
    addStudent: "Add Student",
    addShort: "Add",
    searchStudents: "Search students...",
    noStudentsFound: "No students found matching your search.",
    noStudents: "No students available. Add your first student!",
    view: "View",
    edit: "Edit",
    resetPassword: "Reset Password",
    firstName: "First Name",
    lastName: "Last Name",
    active: "Active",
    inactive: "Inactive",
    activeStatus: "Active Status",
    leaveBlankToKeep: "Leave blank to keep current password",
    passwordResetSuccess: "Password reset successfully",
    errorResettingPassword: "Error resetting password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match",
    passwordRequired: "Password is required",
    resetPasswordDesc: "Enter a new password for this teacher",
    resetting: "Resetting...",
    confirmPasswordReset: "Are you sure you want to reset the password?",
    scheduleClasses: "Schedule Classes",
    remaining: "Remaining",
    
    // Coordinator dashboard
    welcome: "Welcome",
    coordinator: "Coordinator",
    activeTasks: "Active Tasks",
    activeExams: "Active Exams",
    completedItems: "Completed Items",
    taskStatus: "Task Status",
    examStatus: "Exam Status",
    recentTasks: "Recent Tasks",
    recentExams: "Recent Exams",
    noRecentTasks: "No recent tasks",
    noRecentExams: "No recent exams",
    assignedTo: "Assigned to",
    pending: "Pending",
    inProgress: "In Progress",
    reviewed: "Reviewed",
    
    // RescheduleModal translations
    packageFetchError: "We couldn't connect to the server to retrieve your package details. We've set a temporary rescheduling period ending on ${date}. You can still reschedule your class.",
    packageDefaultDuration: "Your class is part of a one-month package that is valid until ${date}. You can only reschedule classes within this period.",
    packageDetailsSummary: "You have ${remainingClasses} classes remaining in your package that expires on ${date}. You can only reschedule classes within this period.",
    packageDefaultMessage: "Your class is part of a one-month package. We've set a default rescheduling period until ${date}.",
    timeExamples: "Examples",
    durationMaintained: "The class duration will remain",
    classDuration: "Class Duration",
    loadingPackageInfo: "Loading package information...",
    enterTime: "Enter Time (24h format)",
    use24HourFormat: "Please use 24-hour format (HH:MM)",
    selectValidDateTime: "Please select a valid date and time",
    cantReschedulePast: "Cannot reschedule to a time in the past",
    cantScheduleBeyondPackage: "Cannot schedule beyond your package end date",
    noClassSelected: "No class was selected for rescheduling. Please try again.",
    hour: "hour",
    hours: "hours",
    
    // Coordinator Panel
    coordinatorPanel: "Coordinator Panel",
    taskManagement: "Task Management",
    examCreation: "Exam Creation",
    teacherSchedules: "Teacher Schedules",
    activeExams: "Active Exams",
    activeTasks: "Active Tasks",
    completedItems: "Completed Items",
    taskStatus: "Task Status",
    examStatus: "Exam Status",
    recentTasks: "Recent Tasks",
    recentExams: "Recent Exams",
    coordinator: "Coordinator",
    teacherPortal: "Teacher Portal",
    
    // Task Management
    createTask: "Create Task",
    taskTitle: "Task Title",
    taskDescription: "Task Description",
    assignTo: "Assign To",
    dueDate: "Due Date",
    deliveryType: "Delivery Type",
    assignedTeacher: "Assigned Teacher",
    createNewTask: "Create New Task",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    reviewed: "Reviewed",
    
    // Exam Management
    createExam: "Create Exam",
    examTitle: "Exam Title",
    examDescription: "Exam Description",
    questionType: "Question Type",
    addQuestion: "Add Question",
    questionText: "Question Text",
    multipleChoice: "Multiple Choice",
    trueFalse: "True/False",
    shortAnswer: "Short Answer",
    longAnswer: "Long Answer",
    option: "Option",
    correctAnswer: "Correct Answer",
    reviewNotes: "Review Notes",
    draft: "Draft",
    assigned: "Assigned",
    approved: "Approved",
    rejected: "Rejected",
    
    // Admin Dashboard
    updateClassStatus: "Update Class Status",
    updateStatusShort: "Update",
    rescheduleDataRefreshed: "Reschedule data refreshed successfully!",
    errorRefreshingReschedules: "Error refreshing reschedules",
    classStatusUpdated: "Class status updated successfully!",
    errorUpdatingClassStatus: "Error updating class status",
    reason: "Reason",
    searchStudents: "Search students...",
    refresh: "Refresh",
    noSearchResults: "No students found matching your search",
    noRecentReschedules: "No recent reschedules",
    
    // Teacher Dashboard translations
    teacherDashboard: "Teacher Dashboard",
    todaysClasses: "Today's Classes",
    pendingTasks: "Pending Tasks",
    assignedStudents: "My Students",
    startClass: "Start Class",
    classSession: "Class Session",
    noStudent: "No student assigned",
    noClassesToday: "You don't have any classes scheduled for today",
    noPendingTasks: "You don't have any pending tasks",
    noAssignedStudents: "You don't have any assigned students yet",
    priority: "Priority",
    normal: "Normal",
    dueDate: "Due date",
    schedule: "Schedule",
    view: "View",
    noEmail: "No email provided",
    errorFetchingStudents: "Could not fetch assigned students",
    errorLoadingDashboard: "Failed to load dashboard data",
    failedToStartClass: "Failed to start class",
  },
  es: {
    // Dashboard
    dashboardOverview: "Vista General del Panel",
    totalStudents: "Total de Estudiantes",
    activePackages: "Paquetes Activos",
    classesToday: "Clases Hoy",
    recentRescheduledClasses: "Clases Reprogramadas Recientes",
    from: "Desde",
    to: "Hasta",
    
    // Common table headers and field names
    workHours: "Horas de Trabajo",
    role: "Rol",
    searchTeachers: "Buscar profesores...",
    loading: "Cargando...",
    noTeachersFound: "No se encontraron profesores que coincidan con tu búsqueda.",
    noTeachers: "No hay profesores disponibles. ¡Agrega tu primer profesor!",
    
    // Admin package management
    packageManagementTitle: "Gestión de Paquetes",
    addPackage: "Agregar Paquete",
    editPackage: "Editar Paquete",
    deletePackage: "Eliminar Paquete",
    confirmDelete: "Confirmar Eliminación",
    confirmDeleteMessage: "¿Estás seguro que deseas eliminar este paquete? Esta acción no se puede deshacer.",
    
    // Coordinator task management
    taskManagement: "Gestión de Tareas",
    assignNewTask: "Asignar Nueva Tarea",
    searchTasks: "Buscar tareas...",
    allStatuses: "Todos los Estados",
    cancelled: "Cancelado",
    
    // Coordinator charts and visualizations
    taskStatusChart: "Gráfico de Estado de Tareas",
    examStatusChart: "Gráfico de Estado de Exámenes",
    teacherPerformanceChart: "Rendimiento de Profesores",
    filterByDate: "Filtrar por Fecha",
    filterByTeacher: "Filtrar por Profesor",
    filterByStatus: "Filtrar por Estado",
    applyFilters: "Aplicar Filtros",
    clearFilters: "Limpiar Filtros",
    showMore: "Mostrar Más",
    showLess: "Mostrar Menos",
    
    // Exam management
    examManagement: "Gestión de Exámenes",
    searchExams: "Buscar exámenes...",
    
    // Form validation and messages
    requiredField: "Este campo es obligatorio",
    invalidEmail: "Correo electrónico inválido",
    invalidPhone: "Número de teléfono inválido",
    invalidDate: "Fecha inválida",
    successMessage: "Operación realizada con éxito",
    errorMessage: "Ha ocurrido un error. Inténtalo de nuevo.",
    savingData: "Guardando datos...",
    loadingData: "Cargando datos...",
    
    // Schedule page
    schedule: "Programar",
    teacherSchedule: "Horario del Profesor",
    givenClasses: "Clases Asignadas",
    startDate: "Fecha de Inicio",
    endDate: "Fecha de Fin",
    teacher: "Profesor",
    date: "Fecha",
    time: "Hora",
    title: "Título",
    students: "Estudiantes",
    noScheduleData: "No se encontraron clases programadas para el período seleccionado.",
    noGivenClassesData: "No se encontraron clases completadas para el período seleccionado.",
    showFilters: "Mostrar Filtros",
    hideFilters: "Ocultar Filtros",
    resetFilters: "Restablecer Filtros",
    allTeachers: "Todos los Profesores",
    noFeedback: "Sin retroalimentación",
    updateTeachers: "Actualizar Profesores",
    
    // Students page
    studentsManagement: "Gestión de Estudiantes",
    addNewStudent: "Agregar Nuevo Estudiante",
    name: "Nombre",
    username: "Usuario",
    location: "Ubicación",
    package: "Paquete",
    classesLeft: "Clases Restantes",
    joinDate: "Fecha de Ingreso",
    actions: "Acciones",
    classes: "clases",
    studentDetails: "Detalles del Estudiante",
    close: "Cerrar",
    cancel: "Cancelar",
    saveChanges: "Guardar Cambios",
    editStudent: "Editar Estudiante",
    surname: "Apellido",
    password: "Contraseña",
    city: "Ciudad",
    country: "País",
    packageType: "Tipo de Paquete",
    classHistory: "Historial de Clases",
    totalClassesTaken: "Total de Clases Tomadas",
    rescheduledClasses: "Clases Reprogramadas",
    times: "veces",
    
    // Sidebar translations
    dashboard: "Panel",
    students: "Estudiantes",
    teachers: "Profesores",
    teacherManagement: "Gestión de Profesores",
    logout: "Cerrar Sesión",
    appName: "YekaCoach",
    packageManagement: 'Gestión de Paquetes',
    addNewPackage: 'Agregar Nuevo Paquete',
    editPackage: 'Editar Paquete',
    packageName: 'Nombre del Paquete',
    description: 'Descripción',
    classesPerMonth: 'Clases por Mes',
    maxReschedules: 'Maximas Reprogramaciones',
    price: 'Precio',
    status: 'Estado',
    save: 'Guardar',
    classCalendar: "Calendario de Clases",
    packageDetails: "Detalles del Paquete",
    validUntil: "Válido hasta",
    classesRemaining: "Clases Restantes",
    reschedulesAvailable: "Reprogramaciones Disponibles",
    rescheduleClass: "Reprogramar Clase",
    confirmReschedule: "Confirmar Reprogramación",
    nextClass: "Próxima Clase",
    canReschedule: "Puede Reprogramar",
    totalClasses: "Total de Clases",
    upcomingClass: "Próxima Clase",
    
    // Student Profile Page
    profile: "Mi Perfil",
    editProfile: "Editar Perfil",
    changePassword: "Cambiar Contraseña",
    personalInfo: "Información Personal",
    history: "Historial",
    contactInformation: "Información de Contacto",
    packageInformation: "Información del Paquete",
    period: "Período",
    upcomingClasses: "Próximas Clases",
    completedClasses: "Clases Completadas",
    feedback: "Retroalimentación",
    reschedulable: "Reprogramable",
    reschedule: "Reprogramar",
    noUpcomingClasses: "No hay clases programadas próximamente",
    completed: "Completada",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    email: "Correo Electrónico",
    phone: "Teléfono",
    
    // Student Dashboard
    studentDashboard: "Panel del Estudiante",
    remainingClasses: "Clases Restantes",
    rescheduleCredits: "Créditos de Reprogramación",
    packageValidUntil: "Paquete Válido Hasta",
    classSchedule: "Horario de Clases",
    outOf: "de",
    creditsAllowed: "créditos permitidos",
    selectNewDate: "Seleccionar Nueva Fecha",
    selectNewTime: "Seleccionar Nueva Hora",
    rescheduleWarning: "* Debes reprogramar al menos 2 horas antes del inicio de la clase",
    confirmReschedule: "Confirmar Reprogramación",
    rescheduleNotAllowed: "Esta clase no puede ser reprogramada ya que ha sido completada.",
    rescheduleTimeLimit: "Las clases solo pueden reprogramarse al menos 2 horas antes de que comiencen.",
    joined: "Se unió",
    contactAdminForChanges: "Por favor contacte al administrador si necesita actualizar la información de su perfil.",
    
    // Login page
    login: "Iniciar Sesión",
    loggingIn: "Iniciando sesión...",
    rememberMe: "Recordarme",
    
    // Landing page
    startNow: "Comenzar Ahora",
    loginNow: "Iniciar Sesión Ahora",
    backToHome: "Volver al Inicio",
    ourFeatures: "Nuestras Características",
    singingLessons: "Clases de Canto",
    flexibleScheduling: "Horarios Flexibles",
    progressTracking: "Seguimiento de Progreso",
    whatOurStudentsSay: "Lo Que Dicen Nuestros Estudiantes",
    readyToStartJourney: "¿Listo para Comenzar Tu Viaje Vocal?",
    joinToday: "Únete a YekaCoach Academy hoy y transforma tus habilidades de canto con orientación experta.",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    allRightsReserved: "Todos los derechos reservados.",
    
    // Password and authentication
    passwordChangeSuccess: "¡Contraseña cambiada con éxito!",
    changePasswordFailed: "No se pudo cambiar la contraseña. Por favor, verifica tu contraseña actual e intenta nuevamente.",
    saving: "Guardando...",
    loginFailed: "Error al iniciar sesión. Por favor, verifica tus credenciales e intenta nuevamente.",
    accountLocked: "Tu cuenta ha sido bloqueada debido a demasiados intentos fallidos de inicio de sesión. Por favor, contacta a un administrador.",
    accountDisabled: "Tu cuenta ha sido deshabilitada. Por favor, contacta a un administrador.",
    accountInactive: "Tu cuenta ha sido desactivada por el administrador. Por favor, contacta a soporte para obtener ayuda.",
    sessionExpired: "Tu sesión ha expirado. Por favor, inicia sesión nuevamente.",
    logoutSuccess: "Has cerrado sesión exitosamente.",
    unauthorized: "No estás autorizado para acceder a esta página.",
    wrongPortalStudent: "Acceso denegado. Este portal es solo para estudiantes. Por favor use el sistema de inicio interno para el personal.",
    wrongPortalInternal: "Acceso denegado. Este portal es solo para el personal. Por favor use el portal de inicio de estudiantes.",
    
    // General UI
    loading: "Cargando, por favor espere...",
    switchToSpanish: "Cambiar a Español",
    switchToEnglish: "Cambiar a Inglés",
    
    // Form validation
    usernameRequired: "El nombre de usuario es obligatorio",
    passwordRequired: "La contraseña es obligatoria",
    currentPasswordRequired: "La contraseña actual es obligatoria",
    newPasswordRequired: "La nueva contraseña es obligatoria",
    confirmPasswordRequired: "Por favor confirma tu contraseña",
    passwordMinLength: "La contraseña debe tener al menos 8 caracteres",
    nameRequired: "El nombre es obligatorio",
    emailRequired: "El correo electrónico es obligatorio",
    emailInvalid: "Ingresa un correo electrónico válido",
    phoneRequired: "El número de teléfono es obligatorio",
    dateRequired: "La fecha es obligatoria", 
    packageRequired: "Debes seleccionar un paquete",
    passwordMismatch: "Las contraseñas no coinciden",
    invalidPasswordFormat: "La contraseña debe contener al menos una letra mayúscula, una minúscula, un número y un carácter especial",
    passwordTooShort: "La contraseña debe tener al menos 6 caracteres",
    
    // Notifications and messages
    loginSuccess: "¡Inicio de sesión exitoso! Bienvenido de nuevo.",
    loginFailed: "Error al iniciar sesión. Por favor verifica tus credenciales e inténtalo nuevamente.",
    unexpectedError: "Ocurrió un error inesperado. Por favor inténtalo más tarde.",
    changesSaved: "¡Cambios guardados con éxito!",
    dataUpdated: "¡Datos actualizados correctamente!",
    dataDeleted: "¡Datos eliminados correctamente!",
    operationSuccess: "¡Operación completada con éxito!",
    operationFailed: "La operación ha fallado. Inténtalo de nuevo.",
    networkError: "Error de conexión. Comprueba tu conexión a Internet.",
    serverError: "Error del servidor. Inténtalo de nuevo más tarde.",
    validationError: "Hay errores de validación. Por favor, comprueba los campos marcados.",
    permissionError: "No tienes permisos para realizar esta acción.",
    dataNotFound: "Los datos solicitados no se han encontrado.",
    sessionExpired: "Tu sesión ha expirado. Por favor, inicia sesión de nuevo.",
    timeoutError: "La operación ha excedido el tiempo de espera. Inténtalo de nuevo.",
    confirmAction: "¿Estás seguro de que quieres realizar esta acción?",
    actionRequired: "Se requiere una acción para continuar.",
    
    // Student Dashboard (adding missing translations)
    currentPackage: "Paquete Actual",
    noPackage: "Sin Paquete",
    scheduledClasses: "Clases Programadas",
    passedClasses: "Clases Pasadas",
    dateFormat: "dddd, D [de] MMMM, YYYY",
    timeFormat: "h:mm A",
    shortDateFormat: "D [de] MMM, YYYY",
    today: "HOY",
    month: "Mes",
    week: "Semana",
    day: "Día",
    agenda: "Agenda",
    date: "Fecha",
    time: "Hora",
    event: "Evento", 
    allDay: "Todo el día",
    previous: "Anterior",
    next: "Siguiente",
    yesterday: "Ayer",
    tomorrow: "Mañana",
    dayNames: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    dayNamesShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    monthNamesShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    minutes: "minutos",
    currentClass: "Clase actual",
    class: "clase",
    today: "HOY",
    fullScreen: "Pantalla Completa",
    exitFullScreen: "Salir de Pantalla Completa",
    loading: "Cargando tus clases...",
    noClasses: "No hay clases programadas",
    noClassesDescription: "No tienes clases programadas en este momento.",
    rescheduled: "Reprogramada",
    cantReschedule: "No se puede reprogramar",
    attended: "Asistida",
    errorLoadingData: "Error al cargar tus datos.",
    rescheduleSuccess: "Clase reprogramada con éxito",
    rescheduleError: "Error al reprogramar la clase. Inténtalo de nuevo.",
    
    // Additional students page translations
    refresh: "Actualizar",
    refreshShort: "Actualizar",
    addStudent: "Agregar Estudiante",
    addShort: "Agregar",
    searchStudents: "Buscar estudiantes...",
    noStudentsFound: "No se encontraron estudiantes que coincidan con tu búsqueda.",
    noStudents: "No hay estudiantes disponibles. ¡Agrega tu primer estudiante!",
    view: "Ver",
    edit: "Editar",
    resetPassword: "Restablecer Contraseña",
    firstName: "Nombre",
    lastName: "Apellido",
    active: "Activo",
    inactive: "Inactivo",
    activeStatus: "Estado Activo",
    leaveBlankToKeep: "Dejar en blanco para mantener la contraseña actual",
    passwordResetSuccess: "Contraseña restablecida con éxito",
    errorResettingPassword: "Error al restablecer la contraseña",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    passwordRequired: "La contraseña es obligatoria",
    resetPasswordDesc: "Ingresa una nueva contraseña para este profesor",
    resetting: "Restableciendo...",
    confirmPasswordReset: "¿Estás seguro de que quieres restablecer la contraseña?",
    scheduleClasses: "Programar Clases",
    remaining: "Restantes",
    
    // Coordinator dashboard
    welcome: "Bienvenido",
    coordinator: "Coordinador",
    activeTasks: "Tareas Activas",
    activeExams: "Exámenes Activos",
    completedItems: "Elementos Completados",
    taskStatus: "Estado de Tareas",
    examStatus: "Estado de Exámenes",
    recentTasks: "Tareas Recientes",
    recentExams: "Exámenes Recientes",
    noRecentTasks: "No hay tareas recientes",
    noRecentExams: "No hay exámenes recientes",
    assignedTo: "Asignado a",
    pending: "Pendiente",
    inProgress: "En Progreso",
    reviewed: "Revisado",
    
    // RescheduleModal translations
    packageFetchError: "No pudimos conectarnos al servidor para recuperar los detalles de tu paquete. Hemos establecido un período de reprogramación temporal que finaliza el ${date}. Aún puedes reprogramar tu clase.",
    packageDefaultDuration: "Tu clase es parte de un paquete de un mes que es válido hasta el ${date}. Solo puedes reprogramar clases dentro de este período.",
    packageDetailsSummary: "Te quedan ${remainingClasses} clases en tu paquete que vence el ${date}. Solo puedes reprogramar clases dentro de este período.",
    packageDefaultMessage: "Tu clase es parte de un paquete de un mes. Hemos establecido un período de reprogramación predeterminado hasta el ${date}.",
    timeExamples: "Ejemplos",
    durationMaintained: "La duración de la clase seguirá siendo",
    classDuration: "Duración de la Clase",
    loadingPackageInfo: "Cargando información del paquete...",
    enterTime: "Ingresa la Hora (formato 24h)",
    use24HourFormat: "Por favor usa el formato de 24 horas (HH:MM)",
    selectValidDateTime: "Por favor selecciona una fecha y hora válidas",
    cantReschedulePast: "No puedes reprogramar a un horario en el pasado",
    cantScheduleBeyondPackage: "No puedes programar más allá de la fecha de finalización de tu paquete",
    noClassSelected: "No se seleccionó ninguna clase para reprogramar. Por favor, inténtalo de nuevo.",
    hour: "hora",
    hours: "horas",
    
    // Coordinator Panel
    coordinatorPanel: "Panel de Coordinador",
    taskManagement: "Gestión de Tareas",
    examCreation: "Creación de Exámenes",
    teacherSchedules: "Horarios de Profesores",
    activeExams: "Exámenes Activos",
    activeTasks: "Tareas Activas",
    completedItems: "Elementos Completados",
    taskStatus: "Estado de Tareas",
    examStatus: "Estado de Exámenes",
    recentTasks: "Tareas Recientes",
    recentExams: "Exámenes Recientes",
    coordinator: "Coordinador",
    teacherPortal: "Portal del Profesor",
    
    // Task Management
    createTask: "Crear Tarea",
    taskTitle: "Título de la Tarea",
    taskDescription: "Descripción de la Tarea",
    assignTo: "Asignar A",
    dueDate: "Fecha Límite",
    deliveryType: "Tipo de Entrega",
    assignedTeacher: "Profesor Asignado",
    createNewTask: "Crear Nueva Tarea",
    pending: "Pendiente",
    inProgress: "En Progreso",
    completed: "Completada",
    reviewed: "Revisada",
    
    // Exam Management
    createExam: "Crear Examen",
    examTitle: "Título del Examen",
    examDescription: "Descripción del Examen",
    questionType: "Tipo de Pregunta",
    addQuestion: "Agregar Pregunta",
    questionText: "Texto de la Pregunta",
    multipleChoice: "Opción Múltiple",
    trueFalse: "Verdadero/Falso",
    shortAnswer: "Respuesta Corta",
    longAnswer: "Respuesta Larga",
    option: "Opción",
    correctAnswer: "Respuesta Correcta",
    reviewNotes: "Notas de Revisión",
    draft: "Borrador",
    assigned: "Asignado",
    approved: "Aprobado",
    rejected: "Rechazado",
    points: "Puntos",
    answers: "Respuestas",
    submitExam: "Enviar Examen",
    reviewExam: "Revisar Examen",
    examSubmitted: "Examen Enviado",
    examReviewed: "Examen Revisado",
    nextQuestion: "Siguiente Pregunta",
    previousQuestion: "Pregunta Anterior",
    completeAllQuestions: "Por favor completa todas las preguntas antes de enviar",
    confirmSubmitExam: "¿Estás seguro de que quieres enviar este examen? No podrás cambiar tus respuestas después.",
    
    // Admin Dashboard
    updateClassStatus: "Actualizar Estado de Clases",
    updateStatusShort: "Actualizar",
    rescheduleDataRefreshed: "¡Datos de reprogramación actualizados exitosamente!",
    errorRefreshingReschedules: "Error al actualizar datos de reprogramación",
    classStatusUpdated: "¡Estado de clases actualizado exitosamente!",
    errorUpdatingClassStatus: "Error al actualizar estado de clases",
    reason: "Razón",
    searchStudents: "Buscar estudiantes...",
    refresh: "Actualizar",
    noSearchResults: "No se encontraron estudiantes que coincidan con tu búsqueda",
    noRecentReschedules: "No hay reprogramaciones recientes",
    
    // Teacher Dashboard translations
    teacherDashboard: "Panel del Profesor",
    todaysClasses: "Clases de Hoy",
    pendingTasks: "Tareas Pendientes",
    assignedStudents: "Mis Estudiantes",
    startClass: "Iniciar Clase",
    classSession: "Sesión de Clase",
    noStudent: "Ningún estudiante asignado",
    noClassesToday: "No tienes clases programadas para hoy",
    noPendingTasks: "No tienes tareas pendientes",
    noAssignedStudents: "Aún no tienes estudiantes asignados",
    priority: "Prioridad",
    normal: "Normal",
    dueDate: "Fecha límite",
    schedule: "Horario",
    view: "Ver",
    noEmail: "No se proporcionó correo electrónico",
    errorFetchingStudents: "No se pudieron obtener los estudiantes asignados",
    errorLoadingDashboard: "Error al cargar los datos del panel",
    failedToStartClass: "Error al iniciar la clase",
    
    // Teacher schedule page
    classDetails: "Detalles de la Clase",
    startTime: "Hora de Inicio",
    endTime: "Hora de Fin", 
    duration: "Duración",
    studentName: "Nombre del Estudiante",
    classCompleted: "Clase Completada",
    classScheduled: "Clase Programada",
    classCancelled: "Clase Cancelada",
    classRescheduled: "Clase Reprogramada",
    availabilitySchedule: "Horario de Disponibilidad",
    setAvailability: "Establecer Disponibilidad",
    addWorkHours: "Añadir Horas de Trabajo",
    addBreakHours: "Añadir Horas de Descanso",
    workHoursAdded: "Horas de trabajo añadidas correctamente",
    breakHoursAdded: "Horas de descanso añadidas correctamente",
    errorAddingHours: "Error al añadir horas",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  // Load language preference from localStorage on initial load
  useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        const savedLanguage = localStorage.getItem('yekacoachacademy_language');
        if (savedLanguage && ['en', 'es'].includes(savedLanguage)) {
          console.log('Loading saved language from localStorage:', savedLanguage);
          setLanguage(savedLanguage);
        }
      } catch (error) {
        console.error('Error loading language preference from localStorage:', error);
      }
    }
  }, []); // Empty dependency array means this runs once on mount

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        console.log('Saving language to localStorage:', language);
        localStorage.setItem('yekacoachacademy_language', language);
      } catch (error) {
        console.error('Error saving language preference to localStorage:', error);
      }
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLanguage = prev === 'en' ? 'es' : 'en';
      console.log('Toggling language from', prev, 'to', newLanguage);
      return newLanguage;
    });
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      toggleLanguage, 
      translations: translations[language] || translations.en 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  // Return a default value if context is not available
  if (!context) {
    return { 
      language: 'en', 
      toggleLanguage: () => console.warn('Language context not available'),
      translations: translations.en
    };
  }
  return context;
}; 